### ISSUE TITLE
Cannot create tables. ConfigError: Missing region in config

### ISSUE THREAD

**Issue by Flexicious-Support** [ryanfitz/vogels#131]
look like the cannot able to createTables.
upto what i see, the DocumentClient not recognize the config.
the region always undefined on the DocumentClient config,
hope fixed soon . i am middle of something. but now its not working.

**Comment by ryanfitz** [comment]
I'm having a hard time understanding the issue you are runnning into. See the getting started section of the README which has details about how the region must be configured

``` javascript
var vogels = require('vogels');
vogels.AWS.config.update({region: "REGION"}); /
```

If you're still running into issues, please post a sample of code to give me a better idea.

**Comment by hcutler** [comment]
When I try to run "node app", I get this error:

`Error creating tables { ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/Users/Hannah-Cutler/Desktop/spring-2017/side-projects/Aspire_PennBook/node_modules/aws-sdk/lib/event_listeners.js:80:45)
    at Request.callListeners (/Users/Hannah-Cutler/Desktop/spring-2017/side-projects/Aspire_PennBook/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/Hannah-Cutler/Desktop/spring-2017/side-projects/Aspire_PennBook/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/Hannah-Cutler/Desktop/spring-2017/side-projects/Aspire_PennBook/node_modules/aws-sdk/lib/event_listeners.js:74:9
    at finish (/Users/Hannah-Cutler/Desktop/spring-2017/side-projects/Aspire_PennBook/node_modules/aws-sdk/lib/config.js:308:7)
    at /Users/Hannah-Cutler/Desktop/spring-2017/side-projects/Aspire_PennBook/node_modules/aws-sdk/lib/config.js:324:9
    at SharedIniFileCredentials.get (/Users/Hannah-Cutler/Desktop/spring-2017/side-projects/Aspire_PennBook/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/Hannah-Cutler/Desktop/spring-2017/side-projects/Aspire_PennBook/node_modules/aws-sdk/lib/config.js:318:24)
    at Config.getCredentials (/Users/Hannah-Cutler/Desktop/spring-2017/side-projects/Aspire_PennBook/node_modules/aws-sdk/lib/config.js:338:9)
    at Request.VALIDATE_CREDENTIALS (/Users/Hannah-Cutler/Desktop/spring-2017/side-projects/Aspire_PennBook/node_modules/aws-sdk/lib/event_listeners.js:69:26)
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2017-02-27T01:06:17.293Z }
`
